// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.Integrations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\posture
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PostureRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The integrations property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.Integrations.IntegrationsRequestBuilder Integrations
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.Integrations.IntegrationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.PostureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostureRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/posture", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.PostureRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PostureRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/posture", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
