// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.UserInvites.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Tailscale.OpenApiClient.UserInvites
{
    /// <summary>
    /// Builds and executes requests for operations under \user-invites
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserInvitesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Tailscale.OpenApiClient.userInvites.item collection</summary>
        /// <param name="position">ID of the user invite.</param>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.UserInvites.Item.WithUserInviteItemRequestBuilder"/></returns>
        public global::Soenneker.Tailscale.OpenApiClient.UserInvites.Item.WithUserInviteItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userInviteId", position);
                return new global::Soenneker.Tailscale.OpenApiClient.UserInvites.Item.WithUserInviteItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.UserInvites.UserInvitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserInvitesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user-invites", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.UserInvites.UserInvitesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserInvitesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user-invites", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
