// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The property name on this target which was updated by the event. When empty, the event didn&apos;t update any fields on this target.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfigurationAuditLogTargetProperty
    {
        [EnumMember(Value = "ACL")]
        #pragma warning disable CS1591
        Acl,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACL_TAGS")]
        #pragma warning disable CS1591
        AclTags,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCOUNT_EMAIL")]
        #pragma warning disable CS1591
        AccountEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "ADDRESS")]
        #pragma warning disable CS1591
        Address,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALLOWED_IPS")]
        #pragma warning disable CS1591
        AllowedIps,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTO_APPROVED_ROUTES")]
        #pragma warning disable CS1591
        AutoApprovedRoutes,
        #pragma warning restore CS1591
        [EnumMember(Value = "ATTRIBUTES")]
        #pragma warning disable CS1591
        Attributes,
        #pragma warning restore CS1591
        [EnumMember(Value = "BILLING_OWNER")]
        #pragma warning disable CS1591
        BillingOwner,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLLECT_SERVICES")]
        #pragma warning disable CS1591
        CollectServices,
        #pragma warning restore CS1591
        [EnumMember(Value = "COLLECT_POSTURE_IDENTITY")]
        #pragma warning disable CS1591
        CollectPostureIdentity,
        #pragma warning restore CS1591
        [EnumMember(Value = "MULLVAD_VPN")]
        #pragma warning disable CS1591
        MullvadVpn,
        #pragma warning restore CS1591
        [EnumMember(Value = "DNS_CONFIG")]
        #pragma warning disable CS1591
        DnsConfig,
        #pragma warning restore CS1591
        [EnumMember(Value = "EMAIL")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXIT_NODE")]
        #pragma warning disable CS1591
        ExitNode,
        #pragma warning restore CS1591
        [EnumMember(Value = "FEATURE")]
        #pragma warning disable CS1591
        Feature,
        #pragma warning restore CS1591
        [EnumMember(Value = "FILE_SHARING")]
        #pragma warning disable CS1591
        FileSharing,
        #pragma warning restore CS1591
        [EnumMember(Value = "HTTPS")]
        #pragma warning disable CS1591
        Https,
        #pragma warning restore CS1591
        [EnumMember(Value = "KEY_EXPIRY_TIME")]
        #pragma warning disable CS1591
        KeyExpiryTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "KEY_EXPIRY")]
        #pragma warning disable CS1591
        KeyExpiry,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOG_EXIT_FLOWS")]
        #pragma warning disable CS1591
        LogExitFlows,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOGSTREAM_ENDPOINT")]
        #pragma warning disable CS1591
        LogstreamEndpoint,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAGIC_DNS")]
        #pragma warning disable CS1591
        MagicDns,
        #pragma warning restore CS1591
        [EnumMember(Value = "MACHINE_AUTH_NEEDED")]
        #pragma warning disable CS1591
        MachineAuthNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "MACHINE_APPROVAL_NEEDED")]
        #pragma warning disable CS1591
        MachineApprovalNeeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_APPROVAL_REQUIRED")]
        #pragma warning disable CS1591
        UserApprovalRequired,
        #pragma warning restore CS1591
        [EnumMember(Value = "MACHINE_NAME")]
        #pragma warning disable CS1591
        MachineName,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAX_KEY_DURATION")]
        #pragma warning disable CS1591
        MaxKeyDuration,
        #pragma warning restore CS1591
        [EnumMember(Value = "NETWORK_FLOW_LOGGING")]
        #pragma warning disable CS1591
        NetworkFlowLogging,
        #pragma warning restore CS1591
        [EnumMember(Value = "GEOSTEERING")]
        #pragma warning disable CS1591
        Geosteering,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE_SHARE")]
        #pragma warning disable CS1591
        NodeShare,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAILNET_INVITE")]
        #pragma warning disable CS1591
        TailnetInvite,
        #pragma warning restore CS1591
        [EnumMember(Value = "PAYMENT_INFO")]
        #pragma warning disable CS1591
        PaymentInfo,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTURE_IDENTITY")]
        #pragma warning disable CS1591
        PostureIdentity,
        #pragma warning restore CS1591
        [EnumMember(Value = "POSTURE_INTEGRATION")]
        #pragma warning disable CS1591
        PostureIntegration,
        #pragma warning restore CS1591
        [EnumMember(Value = "USER_ROLE")]
        #pragma warning disable CS1591
        UserRole,
        #pragma warning restore CS1591
        [EnumMember(Value = "SCIM")]
        #pragma warning disable CS1591
        Scim,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY_EMAIL")]
        #pragma warning disable CS1591
        SecurityEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRIPE_CUSTOMER_ID")]
        #pragma warning disable CS1591
        StripeCustomerId,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIPTION")]
        #pragma warning disable CS1591
        Subscription,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUBSCRIBED_EVENTS")]
        #pragma warning disable CS1591
        SubscribedEvents,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPORT_EMAIL")]
        #pragma warning disable CS1591
        SupportEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECRET")]
        #pragma warning disable CS1591
        Secret,
        #pragma warning restore CS1591
        [EnumMember(Value = "TCD")]
        #pragma warning disable CS1591
        Tcd,
        #pragma warning restore CS1591
        [EnumMember(Value = "TKA")]
        #pragma warning disable CS1591
        Tka,
        #pragma warning restore CS1591
        [EnumMember(Value = "AUTH_PROVIDER")]
        #pragma warning disable CS1591
        AuthProvider,
        #pragma warning restore CS1591
    }
}
