// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of log (always &quot;CONFIG&quot;).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfigType
    {
        [EnumMember(Value = "CONFIG")]
        #pragma warning disable CS1591
        Config,
        #pragma warning restore CS1591
    }
}
