// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1"/>, <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch2"/>, <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch3"/>, <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch4"/>, <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch5"/>, <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigurationAuditLogNew : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1? ConfigurationAuditLogNewBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1 ConfigurationAuditLogNewBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch2? ConfigurationAuditLogNewBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch2 ConfigurationAuditLogNewBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch3? ConfigurationAuditLogNewBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch3 ConfigurationAuditLogNewBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch4? ConfigurationAuditLogNewBranch4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch4 ConfigurationAuditLogNewBranch4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch5? ConfigurationAuditLogNewBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch5 ConfigurationAuditLogNewBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewMember1? ConfigurationAuditLogNewMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewMember1 ConfigurationAuditLogNewMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew();
            result.ConfigurationAuditLogNewBranch1 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1();
            result.ConfigurationAuditLogNewBranch2 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch2();
            result.ConfigurationAuditLogNewBranch3 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch3();
            result.ConfigurationAuditLogNewBranch4 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch4();
            result.ConfigurationAuditLogNewBranch5 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch5();
            result.ConfigurationAuditLogNewMember1 = new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ConfigurationAuditLogNewBranch1 != null || ConfigurationAuditLogNewBranch2 != null || ConfigurationAuditLogNewBranch3 != null || ConfigurationAuditLogNewBranch4 != null || ConfigurationAuditLogNewBranch5 != null || ConfigurationAuditLogNewMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(ConfigurationAuditLogNewBranch1, ConfigurationAuditLogNewBranch2, ConfigurationAuditLogNewBranch3, ConfigurationAuditLogNewBranch4, ConfigurationAuditLogNewBranch5, ConfigurationAuditLogNewMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNewBranch1>(null, ConfigurationAuditLogNewBranch1, ConfigurationAuditLogNewBranch2, ConfigurationAuditLogNewBranch3, ConfigurationAuditLogNewBranch4, ConfigurationAuditLogNewBranch5, ConfigurationAuditLogNewMember1);
        }
    }
}
#pragma warning restore CS0618
