// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The initiator of the action that generated the event, typically an API or user interface, like the Tailscale admin panel.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfigurationAuditLogOrigin
    {
        [EnumMember(Value = "ADMIN_CONSOLE")]
        #pragma warning disable CS1591
        AdminConsole,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONFIG_API")]
        #pragma warning disable CS1591
        ConfigApi,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONTROL")]
        #pragma warning disable CS1591
        Control,
        #pragma warning restore CS1591
        [EnumMember(Value = "IDENTITY_PROVIDER")]
        #pragma warning disable CS1591
        IdentityProvider,
        #pragma warning restore CS1591
        [EnumMember(Value = "NODE")]
        #pragma warning disable CS1591
        Node,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUPPORT_REQUEST")]
        #pragma warning disable CS1591
        SupportRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "STRIPE")]
        #pragma warning disable CS1591
        Stripe,
        #pragma warning restore CS1591
        [EnumMember(Value = "SECURITY_NOTIFICATION")]
        #pragma warning disable CS1591
        SecurityNotification,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEGAL_NOTIFICATION")]
        #pragma warning disable CS1591
        LegalNotification,
        #pragma warning restore CS1591
        [EnumMember(Value = "BORDER0_API")]
        #pragma warning disable CS1591
        Border0Api,
        #pragma warning restore CS1591
    }
}
