// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of change attempted against the `target`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConfigurationAuditLogAction
    {
        [EnumMember(Value = "LOGIN")]
        #pragma warning disable CS1591
        Login,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOGOUT")]
        #pragma warning disable CS1591
        Logout,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATE")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
        [EnumMember(Value = "UPDATE")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "DELETE")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "CANCEL")]
        #pragma warning disable CS1591
        Cancel,
        #pragma warning restore CS1591
        [EnumMember(Value = "REVOKE")]
        #pragma warning disable CS1591
        Revoke,
        #pragma warning restore CS1591
        [EnumMember(Value = "APPROVE")]
        #pragma warning disable CS1591
        Approve,
        #pragma warning restore CS1591
        [EnumMember(Value = "SUSPEND")]
        #pragma warning disable CS1591
        Suspend,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESTORE")]
        #pragma warning disable CS1591
        Restore,
        #pragma warning restore CS1591
        [EnumMember(Value = "ENABLE")]
        #pragma warning disable CS1591
        Enable,
        #pragma warning restore CS1591
        [EnumMember(Value = "DISABLE")]
        #pragma warning disable CS1591
        Disable,
        #pragma warning restore CS1591
        [EnumMember(Value = "ACCEPT")]
        #pragma warning disable CS1591
        Accept,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXPIRED")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUSH_USER")]
        #pragma warning disable CS1591
        PushUser,
        #pragma warning restore CS1591
        [EnumMember(Value = "PUSH_GROUP")]
        #pragma warning disable CS1591
        PushGroup,
        #pragma warning restore CS1591
        [EnumMember(Value = "VERIFY")]
        #pragma warning disable CS1591
        Verify,
        #pragma warning restore CS1591
        [EnumMember(Value = "JOIN_WAITLIST")]
        #pragma warning disable CS1591
        JoinWaitlist,
        #pragma warning restore CS1591
        [EnumMember(Value = "INVITE")]
        #pragma warning disable CS1591
        Invite,
        #pragma warning restore CS1591
        [EnumMember(Value = "JOIN")]
        #pragma warning disable CS1591
        Join,
        #pragma warning restore CS1591
        [EnumMember(Value = "LEAVE")]
        #pragma warning disable CS1591
        Leave,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESEND")]
        #pragma warning disable CS1591
        Resend,
        #pragma warning restore CS1591
        [EnumMember(Value = "MIGRATE_AUTH_PROVIDER")]
        #pragma warning disable CS1591
        MigrateAuthProvider,
        #pragma warning restore CS1591
    }
}
