// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConfigurationAuditLog : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The type of change attempted against the `target`.</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogAction? Action { get; set; }
        /// <summary>Additional information about the event, such as a client-provided reason, if it exists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActionDetails { get; set; }
#nullable restore
#else
        public string ActionDetails { get; set; }
#endif
        /// <summary>The person who caused the action related to this event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogActor? Actor { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogActor Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp recording the time that the audit log rate limiter enqueued the record to be logged at a future time, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeferredAt { get; set; }
#nullable restore
#else
        public string DeferredAt { get; set; }
#endif
        /// <summary>Provided when the configuration change failed to be completed. It is a user-presentable reason for the failure.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Identifier assigned to one or more audit log events, all of which are the result of a single operation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventGroupID { get; set; }
#nullable restore
#else
        public string EventGroupID { get; set; }
#endif
        /// <summary>Timestamp of the audit log event, in RFC 3339 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventTime { get; set; }
#nullable restore
#else
        public string EventTime { get; set; }
#endif
        /// <summary>The value of `target.property` after the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew? New { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew New { get; set; }
#endif
        /// <summary>The value of `target.property`` prior to the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOld? Old { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOld Old { get; set; }
#endif
        /// <summary>The initiator of the action that generated the event, typically an API or user interface, like the Tailscale admin panel.</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOrigin? Origin { get; set; }
        /// <summary>The object of this event&apos;s action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogTarget? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogTarget Target { get; set; }
#endif
        /// <summary>The type of log (always &quot;CONFIG&quot;).</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.ConfigType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLog"/> and sets the default values.
        /// </summary>
        public ConfigurationAuditLog()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLog"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLog CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLog();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogAction>(); } },
                { "actionDetails", n => { ActionDetails = n.GetStringValue(); } },
                { "actor", n => { Actor = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogActor>(global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogActor.CreateFromDiscriminatorValue); } },
                { "deferredAt", n => { DeferredAt = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "eventGroupID", n => { EventGroupID = n.GetStringValue(); } },
                { "eventTime", n => { EventTime = n.GetStringValue(); } },
                { "new", n => { New = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew>(global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew.CreateFromDiscriminatorValue); } },
                { "old", n => { Old = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOld>(global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOld.CreateFromDiscriminatorValue); } },
                { "origin", n => { Origin = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOrigin>(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogTarget>(global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogTarget.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogAction>("action", Action);
            writer.WriteStringValue("actionDetails", ActionDetails);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogActor>("actor", Actor);
            writer.WriteStringValue("deferredAt", DeferredAt);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("eventGroupID", EventGroupID);
            writer.WriteStringValue("eventTime", EventTime);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogNew>("new", New);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOld>("old", Old);
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogOrigin>("origin", Origin);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigurationAuditLogTarget>("target", Target);
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ConfigType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
