// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateKeyRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The value used when matching against the `aud` claim from an OIDC identity token.Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.It is recommended to let Tailscale generate the audience unless the identity provider you are integrating withrequires a specific audience format.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Audience { get; set; }
#nullable restore
#else
        public string Audience { get; set; }
#endif
        /// <summary>`capabilities` is a mapping of resources to permissible actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities? Capabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities Capabilities { get; set; }
#endif
        /// <summary>A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token.Patterns can include `*` characters to match against any character.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestCustomClaimRules? CustomClaimRules { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestCustomClaimRules CustomClaimRules { get; set; }
#endif
        /// <summary>A short string specifying the purpose of the key. Can be a maximum of 50 alphanumeric characters. Hyphens and spaces are also allowed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Specifies the duration in seconds until the key expires. Defaults to 90 days if not supplied.Only applies to auth keys.</summary>
        public long? ExpirySeconds { get; set; }
        /// <summary>The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Issuer { get; set; }
#nullable restore
#else
        public string Issuer { get; set; }
#endif
        /// <summary>The type of key to create. Defaults to &quot;auth&quot; if omitted.</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestKeyType? KeyType { get; set; }
        /// <summary>A list of scopes to grant to the key. At least one scope is required for OAuth clients and federated identities.See [trust credentials scopes](https://tailscale.com/kb/1623/trust-credentials#scopes) for a list of available scopes.Only applies to OAuth clients and federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scopes { get; set; }
#nullable restore
#else
        public List<string> Scopes { get; set; }
#endif
        /// <summary>The pattern used when matching against the `sub` claim from an OIDC identity token.Patterns can include `*` characters to match against any character.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>A list of tags associated to the trust credential. Auth keys created with this credential must have these exact tags, or tags owned by the credential&apos;s tags.Mandatory if the scopes include &quot;devices:core&quot; or &quot;auth_keys&quot;.Only applies to OAuth clients and federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest"/> and sets the default values.
        /// </summary>
        public CreateKeyRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audience", n => { Audience = n.GetStringValue(); } },
                { "capabilities", n => { Capabilities = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities>(global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities.CreateFromDiscriminatorValue); } },
                { "customClaimRules", n => { CustomClaimRules = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestCustomClaimRules>(global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestCustomClaimRules.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expirySeconds", n => { ExpirySeconds = n.GetLongValue(); } },
                { "issuer", n => { Issuer = n.GetStringValue(); } },
                { "keyType", n => { KeyType = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestKeyType>(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("audience", Audience);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities>("capabilities", Capabilities);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestCustomClaimRules>("customClaimRules", CustomClaimRules);
            writer.WriteStringValue("description", Description);
            writer.WriteLongValue("expirySeconds", ExpirySeconds);
            writer.WriteStringValue("issuer", Issuer);
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequestKeyType>("keyType", KeyType);
            writer.WriteCollectionOfPrimitiveValues<string>("scopes", Scopes);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
