// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of key to create. Defaults to &quot;auth&quot; if omitted.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateKeyRequestKeyType
    {
        [EnumMember(Value = "auth")]
        #pragma warning disable CS1591
        Auth,
        #pragma warning restore CS1591
        [EnumMember(Value = "client")]
        #pragma warning disable CS1591
        Client,
        #pragma warning restore CS1591
        [EnumMember(Value = "federated")]
        #pragma warning disable CS1591
        Federated,
        #pragma warning restore CS1591
    }
}
