// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateOrganizationTailnetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>True if the requested tailnet already exists.</summary>
        public bool? AlreadyExists { get; set; }
        /// <summary>RFC3339 timestamp of when the tailnet was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The tailnet name provided in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The DNS suffix used to construct fully qualified domain names for devices in this tailnet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DnsName { get; set; }
#nullable restore
#else
        public string DnsName { get; set; }
#endif
        /// <summary>A stable, globally unique identifier for the tailnet.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>OAuth client credentials with the `all` scope for the newly created tailnet. The secret is returned only once.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.TailnetOAuthClient? OauthClient { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.TailnetOAuthClient OauthClient { get; set; }
#endif
        /// <summary>A stable, globally unique identifier for the organization.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrgId { get; set; }
#nullable restore
#else
        public string OrgId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateOrganizationTailnetResponse"/> and sets the default values.
        /// </summary>
        public CreateOrganizationTailnetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateOrganizationTailnetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.CreateOrganizationTailnetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.CreateOrganizationTailnetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alreadyExists", n => { AlreadyExists = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "dnsName", n => { DnsName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "oauthClient", n => { OauthClient = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetOAuthClient>(global::Soenneker.Tailscale.OpenApiClient.Models.TailnetOAuthClient.CreateFromDiscriminatorValue); } },
                { "orgId", n => { OrgId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("alreadyExists", AlreadyExists);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("dnsName", DnsName);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetOAuthClient>("oauthClient", OauthClient);
            writer.WriteStringValue("orgId", OrgId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
