// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateWebhookRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The endpoint that events are sent to from Tailscale via POST requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndpointUrl { get; set; }
#nullable restore
#else
        public string EndpointUrl { get; set; }
#endif
        /// <summary>The provider type for the webhook destination, or an empty string if none are applicable.Outgoing webhook events are sent in the format expected by the provider type if non-empty.</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.ProviderType? ProviderType { get; set; }
        /// <summary>The list of subscribed events that trigger POST requests to the configured endpoint URL.Learn more about [webhook events](/kb/1213/webhooks#events).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Tailscale.OpenApiClient.Models.SubscriptionsItem?>? Subscriptions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Tailscale.OpenApiClient.Models.SubscriptionsItem?> Subscriptions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateWebhookRequest"/> and sets the default values.
        /// </summary>
        public CreateWebhookRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.CreateWebhookRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.CreateWebhookRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.CreateWebhookRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "endpointUrl", n => { EndpointUrl = n.GetStringValue(); } },
                { "providerType", n => { ProviderType = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ProviderType>(); } },
                { "subscriptions", n => { Subscriptions = n.GetCollectionOfEnumValues<global::Soenneker.Tailscale.OpenApiClient.Models.SubscriptionsItem>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("endpointUrl", EndpointUrl);
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.ProviderType>("providerType", ProviderType);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Tailscale.OpenApiClient.Models.SubscriptionsItem>("subscriptions", Subscriptions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
