// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>
    /// An API access token or Auth Key.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Key : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The value used when matching against the `aud` claim from an OIDC identity token.Specifying the audience is optional as Tailscale will generate a secure audience at creation time by default.It is recommended to let Tailscale generate the audience unless the identity provider you are integrating withrequires a specific audience format.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Audience { get; set; }
#nullable restore
#else
        public string Audience { get; set; }
#endif
        /// <summary>`capabilities` is a mapping of resources to permissible actions.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities? Capabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities Capabilities { get; set; }
#endif
        /// <summary>The created property</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>A map of claim names to pattern strings used to match against arbitrary claims in the OIDC identity token.Patterns can include `*` characters to match against any character.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCustomClaimRulesProperty? CustomClaimRules { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyCustomClaimRulesProperty CustomClaimRules { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The expires property</summary>
        public DateTimeOffset? Expires { get; set; }
        /// <summary>Duration in seconds until the key expires.Only applies to auth keys.</summary>
        public long? ExpirySeconds { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Response for a revoked (deleted) or expired key will have an `invalid` field set to true.</summary>
        public bool? Invalid { get; set; }
        /// <summary>The issuer of the OIDC identity token used in the token exchange. Must be a valid and publicly reachable https:// URL.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Issuer { get; set; }
#nullable restore
#else
        public string Issuer { get; set; }
#endif
        /// <summary>The secret key material (only populated at creation time).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KeyProp { get; set; }
#nullable restore
#else
        public string KeyProp { get; set; }
#endif
        /// <summary>The type of key. Can be one of &quot;auth&quot;, &quot;client&quot;, &quot;federated&quot;, or &quot;api&quot;.- &quot;auth&quot; refers to machine auth keys.- &quot;client&quot; refers to OAuth clients.- &quot;federated&quot; refers to federated identities.- &quot;api&quot; refers to personal API access tokens or tokens generated using an OAuth client or federated identity.</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Models.KeyKeyType? KeyType { get; set; }
        /// <summary>The revoked property</summary>
        public DateTimeOffset? Revoked { get; set; }
        /// <summary>A list of scopes granted to the key.Only applies to OAuth clients, API access tokens, and federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Scopes { get; set; }
#nullable restore
#else
        public List<string> Scopes { get; set; }
#endif
        /// <summary>The pattern used when matching against the `sub` claim from an OIDC identity token.This pattern can include `*` characters to match against any character.Only applies to federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>A list of tags associated to the trust credential. Auth keys created with this client must have these exact tags, or tags owned by the client&apos;s tags. Mandatory if the scopes include &quot;devices:core&quot; or &quot;auth_keys&quot;. Only applies to OAuth clients and federated identities.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The updated property</summary>
        public DateTimeOffset? Updated { get; set; }
        /// <summary>ID of the user who created this key, empty for keys created by trust credentials.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserId { get; set; }
#nullable restore
#else
        public string UserId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.Key"/> and sets the default values.
        /// </summary>
        public Key()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.Key"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.Key CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.Key();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "audience", n => { Audience = n.GetStringValue(); } },
                { "capabilities", n => { Capabilities = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities>(global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities.CreateFromDiscriminatorValue); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "customClaimRules", n => { CustomClaimRules = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCustomClaimRulesProperty>(global::Soenneker.Tailscale.OpenApiClient.Models.KeyCustomClaimRulesProperty.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expires", n => { Expires = n.GetDateTimeOffsetValue(); } },
                { "expirySeconds", n => { ExpirySeconds = n.GetLongValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "invalid", n => { Invalid = n.GetBoolValue(); } },
                { "issuer", n => { Issuer = n.GetStringValue(); } },
                { "key", n => { KeyProp = n.GetStringValue(); } },
                { "keyType", n => { KeyType = n.GetEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyKeyType>(); } },
                { "revoked", n => { Revoked = n.GetDateTimeOffsetValue(); } },
                { "scopes", n => { Scopes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "updated", n => { Updated = n.GetDateTimeOffsetValue(); } },
                { "userId", n => { UserId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("audience", Audience);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCapabilities>("capabilities", Capabilities);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyCustomClaimRulesProperty>("customClaimRules", CustomClaimRules);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("expires", Expires);
            writer.WriteLongValue("expirySeconds", ExpirySeconds);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("invalid", Invalid);
            writer.WriteStringValue("issuer", Issuer);
            writer.WriteStringValue("key", KeyProp);
            writer.WriteEnumValue<global::Soenneker.Tailscale.OpenApiClient.Models.KeyKeyType>("keyType", KeyType);
            writer.WriteDateTimeOffsetValue("revoked", Revoked);
            writer.WriteCollectionOfPrimitiveValues<string>("scopes", Scopes);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteDateTimeOffsetValue("updated", Updated);
            writer.WriteStringValue("userId", UserId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
