// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of key. Can be one of &quot;auth&quot;, &quot;client&quot;, &quot;federated&quot;, or &quot;api&quot;.- &quot;auth&quot; refers to machine auth keys.- &quot;client&quot; refers to OAuth clients.- &quot;federated&quot; refers to federated identities.- &quot;api&quot; refers to personal API access tokens or tokens generated using an OAuth client or federated identity.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum KeyKeyType
    {
        [EnumMember(Value = "auth")]
        #pragma warning disable CS1591
        Auth,
        #pragma warning restore CS1591
        [EnumMember(Value = "client")]
        #pragma warning disable CS1591
        Client,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
        [EnumMember(Value = "federated")]
        #pragma warning disable CS1591
        Federated,
        #pragma warning restore CS1591
    }
}
