// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The compression algorithm with which to compress logs. `none` disables compression. Defaults to `none`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogstreamEndpointConfigurationCompressionFormat
    {
        [EnumMember(Value = "zstd")]
        #pragma warning disable CS1591
        Zstd,
        #pragma warning restore CS1591
        [EnumMember(Value = "gzip")]
        #pragma warning disable CS1591
        Gzip,
        #pragma warning restore CS1591
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
    }
}
