// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of system to which logs are being streamed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogstreamEndpointConfigurationDestinationType
    {
        [EnumMember(Value = "splunk")]
        #pragma warning disable CS1591
        Splunk,
        #pragma warning restore CS1591
        [EnumMember(Value = "elastic")]
        #pragma warning disable CS1591
        Elastic,
        #pragma warning restore CS1591
        [EnumMember(Value = "panther")]
        #pragma warning disable CS1591
        Panther,
        #pragma warning restore CS1591
        [EnumMember(Value = "cribl")]
        #pragma warning disable CS1591
        Cribl,
        #pragma warning restore CS1591
        [EnumMember(Value = "crowdstrike")]
        #pragma warning disable CS1591
        Crowdstrike,
        #pragma warning restore CS1591
        [EnumMember(Value = "datadog")]
        #pragma warning disable CS1591
        Datadog,
        #pragma warning restore CS1591
        [EnumMember(Value = "axiom")]
        #pragma warning disable CS1591
        Axiom,
        #pragma warning restore CS1591
        [EnumMember(Value = "s3")]
        #pragma warning disable CS1591
        S3,
        #pragma warning restore CS1591
    }
}
