// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of log that is streamed to this endpoint.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum LogType
    {
        [EnumMember(Value = "configuration")]
        #pragma warning disable CS1591
        Configuration,
        #pragma warning restore CS1591
        [EnumMember(Value = "network")]
        #pragma warning disable CS1591
        Network,
        #pragma warning restore CS1591
    }
}
