// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The device posture provider.Required on POST requests, ignored on PATCH requests.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostureIntegrationProvider
    {
        [EnumMember(Value = "falcon")]
        #pragma warning disable CS1591
        Falcon,
        #pragma warning restore CS1591
        [EnumMember(Value = "intune")]
        #pragma warning disable CS1591
        Intune,
        #pragma warning restore CS1591
        [EnumMember(Value = "jamfpro")]
        #pragma warning disable CS1591
        Jamfpro,
        #pragma warning restore CS1591
        [EnumMember(Value = "kandji")]
        #pragma warning disable CS1591
        Kandji,
        #pragma warning restore CS1591
        [EnumMember(Value = "kolide")]
        #pragma warning disable CS1591
        Kolide,
        #pragma warning restore CS1591
        [EnumMember(Value = "sentinelone")]
        #pragma warning disable CS1591
        Sentinelone,
        #pragma warning restore CS1591
    }
}
