// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PreviewRuleMatches200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The matches property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200ResponseMatchesItem>? Matches { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200ResponseMatchesItem> Matches { get; set; }
#endif
        /// <summary>Echoes the `previewFor` provided in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewFor { get; set; }
#nullable restore
#else
        public string PreviewFor { get; set; }
#endif
        /// <summary>Echoes the `type` provided in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200Response"/> and sets the default values.
        /// </summary>
        public PreviewRuleMatches200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "matches", n => { Matches = n.GetCollectionOfObjectValues<global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200ResponseMatchesItem>(global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200ResponseMatchesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "previewFor", n => { PreviewFor = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Tailscale.OpenApiClient.Models.PreviewRuleMatches200ResponseMatchesItem>("matches", Matches);
            writer.WriteStringValue("previewFor", PreviewFor);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
