// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The approval level of the device hosting the Service.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ServiceHostInfoApprovalLevel
    {
        [EnumMember(Value = "not-approved")]
        #pragma warning disable CS1591
        NotApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "approved:auto")]
        #pragma warning disable CS1591
        ApprovedColonAuto,
        #pragma warning restore CS1591
        [EnumMember(Value = "approved:manual")]
        #pragma warning disable CS1591
        ApprovedColonManual,
        #pragma warning restore CS1591
    }
}
