// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SetCustomDevicePostureAttributesRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An optional comment indicating a reason why an attribute is set,which will be added to the audit log.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>An optional expiry time for a given posture attribute. If set, Tailscalewill automatically remove the attribute within a few minutes after the specifiedtime.</summary>
        public DateTimeOffset? Expiry { get; set; }
        /// <summary>A value can be either a string, number or boolean.A string value can have a maximum length of 50 characters,and can only contain letters, numbers, underscores, and periods.A number value is an integer and must be a JSON safe number (up to 2^53 - 1).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequestValue? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequestValue Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequest"/> and sets the default values.
        /// </summary>
        public SetCustomDevicePostureAttributesRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "expiry", n => { Expiry = n.GetDateTimeOffsetValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequestValue>(global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequestValue.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteDateTimeOffsetValue("expiry", Expiry);
            writer.WriteObjectValue<global::Soenneker.Tailscale.OpenApiClient.Models.SetCustomDevicePostureAttributesRequestValue>("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
