// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The type of the key being updated.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SetKeyRequestKeyType
    {
        [EnumMember(Value = "client")]
        #pragma warning disable CS1591
        Client,
        #pragma warning restore CS1591
        [EnumMember(Value = "federated")]
        #pragma warning disable CS1591
        Federated,
        #pragma warning restore CS1591
    }
}
