// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The tailnet user role to assign to the invited user upon accepting the invite.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserInviteRole
    {
        [EnumMember(Value = "member")]
        #pragma warning disable CS1591
        Member,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "it-admin")]
        #pragma warning disable CS1591
        ItAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "network-admin")]
        #pragma warning disable CS1591
        NetworkAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "billing-admin")]
        #pragma warning disable CS1591
        BillingAdmin,
        #pragma warning restore CS1591
        [EnumMember(Value = "auditor")]
        #pragma warning disable CS1591
        Auditor,
        #pragma warning restore CS1591
    }
}
