// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    /// <summary>The status of the user.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UserStatus
    {
        [EnumMember(Value = "active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "idle")]
        #pragma warning disable CS1591
        Idle,
        #pragma warning restore CS1591
        [EnumMember(Value = "suspended")]
        #pragma warning disable CS1591
        Suspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "needs-approval")]
        #pragma warning disable CS1591
        NeedsApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "over-billing-limit")]
        #pragma warning disable CS1591
        OverBillingLimit,
        #pragma warning restore CS1591
    }
}
