// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WebhookSubscriptionsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "nodeCreated")]
        #pragma warning disable CS1591
        NodeCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeNeedsApproval")]
        #pragma warning disable CS1591
        NodeNeedsApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeApproved")]
        #pragma warning disable CS1591
        NodeApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeKeyExpiringInOneDay")]
        #pragma warning disable CS1591
        NodeKeyExpiringInOneDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeKeyExpired")]
        #pragma warning disable CS1591
        NodeKeyExpired,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeDeleted")]
        #pragma warning disable CS1591
        NodeDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeSigned")]
        #pragma warning disable CS1591
        NodeSigned,
        #pragma warning restore CS1591
        [EnumMember(Value = "nodeNeedsSignature")]
        #pragma warning disable CS1591
        NodeNeedsSignature,
        #pragma warning restore CS1591
        [EnumMember(Value = "policyUpdate")]
        #pragma warning disable CS1591
        PolicyUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "userCreated")]
        #pragma warning disable CS1591
        UserCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "userNeedsApproval")]
        #pragma warning disable CS1591
        UserNeedsApproval,
        #pragma warning restore CS1591
        [EnumMember(Value = "userSuspended")]
        #pragma warning disable CS1591
        UserSuspended,
        #pragma warning restore CS1591
        [EnumMember(Value = "userRestored")]
        #pragma warning disable CS1591
        UserRestored,
        #pragma warning restore CS1591
        [EnumMember(Value = "userDeleted")]
        #pragma warning disable CS1591
        UserDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "userApproved")]
        #pragma warning disable CS1591
        UserApproved,
        #pragma warning restore CS1591
        [EnumMember(Value = "userRoleUpdated")]
        #pragma warning disable CS1591
        UserRoleUpdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "subnetIPForwardingNotEnabled")]
        #pragma warning disable CS1591
        SubnetIpForwardingNotEnabled,
        #pragma warning restore CS1591
        [EnumMember(Value = "exitNodeIPForwardingNotEnabled")]
        #pragma warning disable CS1591
        ExitNodeIpForwardingNotEnabled,
        #pragma warning restore CS1591
    }
}
