// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Models;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Acl;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.AwsExternalId;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Contacts;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.DeviceAttributes;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Dns;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.OauthApps;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.UserInvites;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Users;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithTailnetItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The acl property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Acl.AclRequestBuilder Acl
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Acl.AclRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The awsExternalId property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.AwsExternalId.AwsExternalIdRequestBuilder AwsExternalId
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.AwsExternalId.AwsExternalIdRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The contacts property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Contacts.ContactsRequestBuilder Contacts
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Contacts.ContactsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deviceAttributes property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.DeviceAttributes.DeviceAttributesRequestBuilder DeviceAttributes
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.DeviceAttributes.DeviceAttributesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The devices property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder Devices
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The dns property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Dns.DnsRequestBuilder Dns
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Dns.DnsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The keys property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder Keys
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The logging property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.LoggingRequestBuilder Logging
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.LoggingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauthApps property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.OauthApps.OauthAppsRequestBuilder OauthApps
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.OauthApps.OauthAppsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The posture property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.PostureRequestBuilder Posture
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Posture.PostureRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.ServicesRequestBuilder Services
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The settings property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder Settings
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The userInvites property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.UserInvites.UserInvitesRequestBuilder UserInvites
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.UserInvites.UserInvitesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTailnetItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithTailnetItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}", rawUrl)
        {
        }
        /// <summary>
        /// Delete the specified tailnet and all of its users, devices, and configuration.[API-only tailnets](https://tailscale.com/docs/features/tailnet-creation-api) can be deleted using an accesstoken for the tailnet being deleted. You can get a tailnet-specific access token by exchanging either the OAuthclient credentials returned when the tailnet was created or an OAuth client from the creating tailnet that hasthe `all` scope.OAuth Scope: `all`.
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete the specified tailnet and all of its users, devices, and configuration.[API-only tailnets](https://tailscale.com/docs/features/tailnet-creation-api) can be deleted using an accesstoken for the tailnet being deleted. You can get a tailnet-specific access token by exchanging either the OAuthclient credentials returned when the tailnet was created or an OAuth client from the creating tailnet that hasthe `all` scope.OAuth Scope: `all`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
