// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Models;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\keys
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeysRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Tailscale.OpenApiClient.tailnet.item.keys.item collection</summary>
        /// <param name="position">The id of the key.The key ID can be found in the [admin console](https://login.tailscale.com/admin/settings/keys).</param>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.Item.WithKeyItemRequestBuilder"/></returns>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.Item.WithKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("keyId", position);
                return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.Item.WithKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/keys", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/keys", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of active auth keys, API access tokens and trust credentials.If the parameter {all} was not specified, the set of keys returned depends on the access token used to make the request:- If the API call is made with a user-owned API access token, this returns only the keys owned by that user.- If the API call is made with an access token derived from an OAuth client, this returns all OAuth clients for the tailnet.- If the API call is made with an access token derived from a federated identity, this returns all federated identities for the tailnet.OAuth Scope: `api_access_tokens:read` grants access to personal API access tokens.OAuth Scope: `auth_keys:read` grants access to machine auth keys.OAuth Scope: `oauth_keys:read` grants access to OAuth clients and OAuth tokens.OAuth Scope: `federated_keys:read` grants access to federated identities.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetKeys200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetKeys200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetKeys200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetKeys200Response>(requestInfo, global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetKeys200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates a new [auth key](https://tailscale.com/kb/1085/), or [trust credential](https://tailscale.com/kb/1623/) in the specified tailnet.Trust credentials include [OAuth clients](https://tailscale.com/kb/1215/) and [federated identities](https://tailscale.com/kb/1581/).The key will be associated with the user who owns the API access token used to make this call,or, if the call is made with an access token derived from an OAuth client or federated identity, the key will be owned by the tailnet.Returns a JSON object with the generated key.The key should be recorded and kept safe and secure because it wields the capabilities or scopes specified in the request.The identity of the key is embedded in the key itself and can be used to perform operations on the key (e.g., revoking it or retrieving information about it).The full key can no longer be retrieved after the initial response.OAuth Scope: `auth_keys` grants access to create machine auth keys.OAuth Scope: `oauth_keys` grants access to create OAuth clients.OAuth Scope: `federated_keys` grants access to created federated identities.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.Key"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.Key?> PostAsync(global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.Key> PostAsync(global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Tailscale.OpenApiClient.Models.Key>(requestInfo, global::Soenneker.Tailscale.OpenApiClient.Models.Key.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of active auth keys, API access tokens and trust credentials.If the parameter {all} was not specified, the set of keys returned depends on the access token used to make the request:- If the API call is made with a user-owned API access token, this returns only the keys owned by that user.- If the API call is made with an access token derived from an OAuth client, this returns all OAuth clients for the tailnet.- If the API call is made with an access token derived from a federated identity, this returns all federated identities for the tailnet.OAuth Scope: `api_access_tokens:read` grants access to personal API access tokens.OAuth Scope: `auth_keys:read` grants access to machine auth keys.OAuth Scope: `oauth_keys:read` grants access to OAuth clients and OAuth tokens.OAuth Scope: `federated_keys:read` grants access to federated identities.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder.KeysRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, "{+baseurl}/tailnet/{tailnet}/keys?all={all}", PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new [auth key](https://tailscale.com/kb/1085/), or [trust credential](https://tailscale.com/kb/1623/) in the specified tailnet.Trust credentials include [OAuth clients](https://tailscale.com/kb/1215/) and [federated identities](https://tailscale.com/kb/1581/).The key will be associated with the user who owns the API access token used to make this call,or, if the call is made with an access token derived from an OAuth client or federated identity, the key will be owned by the tailnet.Returns a JSON object with the generated key.The key should be recorded and kept safe and secure because it wields the capabilities or scopes specified in the request.The identity of the key is embedded in the key itself and can be used to perform operations on the key (e.g., revoking it or retrieving information about it).The full key can no longer be retrieved after the initial response.OAuth Scope: `auth_keys` grants access to create machine auth keys.OAuth Scope: `oauth_keys` grants access to create OAuth clients.OAuth Scope: `federated_keys` grants access to created federated identities.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Tailscale.OpenApiClient.Models.CreateKeyRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Keys.KeysRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of active auth keys, API access tokens and trust credentials.If the parameter {all} was not specified, the set of keys returned depends on the access token used to make the request:- If the API call is made with a user-owned API access token, this returns only the keys owned by that user.- If the API call is made with an access token derived from an OAuth client, this returns all OAuth clients for the tailnet.- If the API call is made with an access token derived from a federated identity, this returns all federated identities for the tailnet.OAuth Scope: `api_access_tokens:read` grants access to personal API access tokens.OAuth Scope: `auth_keys:read` grants access to machine auth keys.OAuth Scope: `oauth_keys:read` grants access to OAuth clients and OAuth tokens.OAuth Scope: `federated_keys:read` grants access to federated identities.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeysRequestBuilderGetQueryParameters 
        {
            /// <summary>If set to true, this will return all auth keys, API access tokens and OAuth clients for the tailnet.</summary>
            [QueryParameter("all")]
            public bool? All { get; set; }
        }
    }
}
#pragma warning restore CS0618
