// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\settings
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SettingsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/settings", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SettingsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/settings", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve the settings for a specific tailnet.OAuth Scope: `feature_settings:read` - required to view all settings except those governed by the below scopes.OAuth Scope: `logs:network:read` - required to view the `networkFlowLoggingOn` setting.OAuth Scope: `networking_settings:read` - required to view the `httpsCertificates` setting.OAuth Scope: `policy_file:read` - required to view the `aclsExternallyManagedOn` &amp; `aclsExternalLink` settings.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings>(requestInfo, global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update the settings for a specific tailnet.OAuth Scope: `feature_settings` - required to update all settings except those governed by the below scopes.OAuth Scope: `logs:network` - required to update the `networkFlowLoggingOn` setting.OAuth Scope: `networking_settings` - required to update the `httpsCertificates` setting.OAuth Scope: `policy_file` - required to update the `aclsExternallyManagedOn` &amp; `aclsExternalLink` settings.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings"/></returns>
        /// <param name="body">Settings for a tailnet.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings?> PatchAsync(global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings> PatchAsync(global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings>(requestInfo, global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve the settings for a specific tailnet.OAuth Scope: `feature_settings:read` - required to view all settings except those governed by the below scopes.OAuth Scope: `logs:network:read` - required to view the `networkFlowLoggingOn` setting.OAuth Scope: `networking_settings:read` - required to view the `httpsCertificates` setting.OAuth Scope: `policy_file:read` - required to view the `aclsExternallyManagedOn` &amp; `aclsExternalLink` settings.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update the settings for a specific tailnet.OAuth Scope: `feature_settings` - required to update all settings except those governed by the below scopes.OAuth Scope: `logs:network` - required to update the `networkFlowLoggingOn` setting.OAuth Scope: `networking_settings` - required to update the `httpsCertificates` setting.OAuth Scope: `policy_file` - required to update the `aclsExternallyManagedOn` &amp; `aclsExternalLink` settings.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Settings for a tailnet.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Tailscale.OpenApiClient.Models.TailnetSettings body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Settings.SettingsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
