// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Configuration;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Item;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Network;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\logging
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LoggingRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The configuration property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Configuration.ConfigurationRequestBuilder Configuration
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Configuration.ConfigurationRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The network property</summary>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Network.NetworkRequestBuilder Network
        {
            get => new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Network.NetworkRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.Tailscale.OpenApiClient.tailnet.item.logging.item collection</summary>
        /// <param name="position">The type of log.</param>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Item.WithLogTypeItemRequestBuilder"/></returns>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Item.WithLogTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("logType", position);
                return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.Item.WithLogTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.LoggingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoggingRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/logging", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Logging.LoggingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LoggingRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/logging", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
