// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\services\{serviceName}\device
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Tailscale.OpenApiClient.tailnet.item.services.item.device.item collection</summary>
        /// <param name="position">ID of the device. Using the device&apos;s `nodeId` is preferred, but its numeric `id` value can also be used.</param>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.Item.WithDeviceItemRequestBuilder"/></returns>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.Item.WithDeviceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deviceId", position);
                return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.Item.WithDeviceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.DeviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/services/{serviceName}/device", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Services.Item.Device.DeviceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeviceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/services/{serviceName}/device", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
