// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet\{tailnet}\devices
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DevicesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DevicesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/devices{?%3Cfield%3E%3D%3Cvalue%3E%20filters*,fields*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DevicesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet/{tailnet}/devices{?%3Cfield%3E%3D%3Cvalue%3E%20filters*,fields*}", rawUrl)
        {
        }
        /// <summary>
        /// Lists the devices in a tailnet.OAuth Scope: `devices:core:read`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetDevices200Response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Tailscale.OpenApiClient.Models.Error">When receiving a 504 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetDevices200Response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder.DevicesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetDevices200Response> GetAsync(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder.DevicesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "404", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
                { "504", global::Soenneker.Tailscale.OpenApiClient.Models.Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetDevices200Response>(requestInfo, global::Soenneker.Tailscale.OpenApiClient.Models.ListTailnetDevices200Response.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Lists the devices in a tailnet.OAuth Scope: `devices:core:read`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder.DevicesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder.DevicesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.Devices.DevicesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Lists the devices in a tailnet.OAuth Scope: `devices:core:read`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DevicesRequestBuilderGetQueryParameters 
        {
            /// <summary>Optionally controls whether the response returns **all** fields or only a predefined subset of fields.Currently, there are two supported options:- **`all`:** return all fields in the response- **`default`:** return the following fields  - `addresses`  - `id`  - `nodeId`  - `user`  - `name`  - `hostname`  - `clientVersion`  - `updateAvailable`  - `os`  - `created`  - `connectedToControl`  - `lastSeen`  - `keyExpiryDisabled`  - `expires`  - `authorized`  - `isExternal`  - `machineKey`  - `nodeKey`  - `blocksIncomingConnections`  - `tailnetLockKey`  - `tailnetLockError`  - `tags`  - `isEphemeral`If the `fields` parameter is not supplied, then the default (limited fields) option is used.</summary>
            [QueryParameter("fields")]
            public global::Soenneker.Tailscale.OpenApiClient.Models.Fields? Fields { get; set; }
            /// <summary>This endpoint supports server-side filtering of devices by specifying oneor more filters in the form `&lt;field&gt;=&lt;value&gt;`. Fields must be a top-leveldevice property - e.g. `isEphemeral`, `tags`, `hostname`, etc. Values arematched as _exact_ matches. Properties with simple types (strings, numbers,dates, etc) and lists are supported. Properties that are complex objects(e.g. `clientConnectivity`) are not supported. When multiple parameters areprovided, the server performs a logical `AND` across all filter parametersbefore returning results. For example,`isEphemeral=true&amp;tags=tag:prod&amp;tags=tag:subnetrouter` would return deviceswhere `isEphemeral` is `true` and `tags` contains both `tag:prod` and`tag:subnetrouter`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%3Cfield%3E%3D%3Cvalue%3E%20filters")]
            public string? Fieldvaluefilters { get; set; }
#nullable restore
#else
            [QueryParameter("%3Cfield%3E%3D%3Cvalue%3E%20filters")]
            public string Fieldvaluefilters { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
