// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Tailscale.OpenApiClient.Tailnet.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Tailscale.OpenApiClient.Tailnet
{
    /// <summary>
    /// Builds and executes requests for operations under \tailnet
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TailnetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Tailscale.OpenApiClient.tailnet.item collection</summary>
        /// <param name="position">The tailnet ID. Tailnets created before Oct 2025 can still use the legacy ID, but the Tailnet ID is the preferred identifier.When specifying a tailnet in the API, you can:- Provide a dash (`-`) to reference the default tailnet of the access token being used to make the API call.  This is the best option for most users.  Your API calls would start:  ```sh  curl &quot;https://api.tailscale.com/api/v2/tailnet/-/...&quot;  ```- Provide the **tailnet ID** found on the **[General Settings](https://login.tailscale.com/admin/settings/general)**  page of the Tailscale admin console.  For example, if your tailnet ID name is `T1234CNTRL`, your API calls would start:  ```sh  curl &quot;https://api.tailscale.com/api/v2/tailnet/T1234CNTRL/...&quot;  ```  Learn more about [tailnet ID](https://tailscale.com/kb/1217/tailnet-name#tailnet-id).</param>
        /// <returns>A <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder"/></returns>
        public global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("tailnet", position);
                return new global::Soenneker.Tailscale.OpenApiClient.Tailnet.Item.WithTailnetItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.TailnetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TailnetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Tailscale.OpenApiClient.Tailnet.TailnetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TailnetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/tailnet", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
